### ISSUE TITLE
typo in mtransform.go:RotatePoint()

### ISSUE THREAD

**Issue by tinkerator** [rustyoz/Mtransform#3]
This code looks like it has a typo:

https://github.com/rustyoz/Mtransform/blob/master/mtransform.go#L77
```
func (t *Transform) RotatePoint(angle float64, x float64, y float64) {
       t.Translate(x, y)
       t.RotateOrigin(angle)
       t.Translate(-x, -x)
}
```
The final translation should likely be `t.Translate(-x, -y)`.

**Comment by rustyoz** [comment]
fixed
